@startuml activ

|Utilisateur|
start
:inscrire;
:validerInscription;
:confirmationInscription;

|Utilisateur|
:seConnecter;
:verifierIdentifiants;
:confirmationConnexion;

|Utilisateur|
:rechercherAnnonces;
:rechercher;
:afficherRésultats;

|Utilisateur|
:reserverMaison;
:verifierDisponibilite;
:traiterPaiement;
:confirmationReservation;

|Administrateur|
:gererUtilisateurs;
:afficherListeUtilisateurs;
:gestionUtilisateur;

|Administrateur|
:modererAnnonces;
:afficherListeAnnonces;
:gestionAnnonce;

stop

@enduml
